### PR TITLE
fix for joomla-cypress 1.1.0

### PR DESCRIPTION
**Pull request by alikon**
from [43726](https://github.com/joomla/joomla-cms/pull/43726/)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
still need some more investigations for Featured failure

**Comment by alikon** [comment]
should be ready

**Review by muhme — CHANGES_REQUESTED** [review]
Great 👍 4 of the 6 'hacks' are replaced by down-merges or improving the tests, thank you 👍

Tested on macOS there is one error:
```
npx cypress run --spec tests/System/integration/site/modules/mod_related_items/Default.cy.js
  Test in frontend that the related items module
    1) "after each" hook for "can display a list of related articles based on the metakey field"
  1 failing
  1) Test in frontend that the related items module
       "after each" hook for "can display a list of related articles based on the metakey field":
     Error: Unwanted PHP Deprecated: "  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in <b>/joomla-cms/libraries/src/Date/Date.php</b> on line <b>126</b>"
```
(not visible in screenshot, therefore applied https://github.com/joomla-projects/joomla-cypress/pull/26 to see the error)

and what about the remaining two 'HACKS'? 😛

**Comment by alikon** [comment]
I thought mod_related_items was ok, at least in my setup, on my setup i don't see others 😿

**Comment by muhme** [comment]
Sorry for the work :sweat:, but in site/components/com_newsfeed there is a 'HACK' in NewsFeed.cy.js and another one in Category.cy.js - it would be very nice if you could remove these as well – then we are clean 🙏

**Comment by alikon** [comment]
@muhme  re-check when you can

**Review by muhme — APPROVED** [review]
Great job – all HACKs are replaced 👍 thank you very much

Quick-Checked on macOS, there is is one apostrophe missing, but that doesn't matter, i am able to insert it. And everything is running.

I will complete the joomla-cms PR afterwards and run tests on Windows and Linux too.

**Pull request merged**
